"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Download, Loader2 } from "lucide-react";

interface DownloadPDFButtonProps {
  reportRef: React.RefObject<HTMLDivElement | null>;
  clientName: string;
  startDate: string;
  endDate: string;
  className?: string;
}

export function DownloadPDFButton({
  reportRef,
  clientName,
  startDate,
  endDate,
  className,
}: DownloadPDFButtonProps) {
  const [isGenerating, setIsGenerating] = useState(false);

  const handleDownloadPDF = async () => {
    if (!reportRef.current) return;

    try {
      setIsGenerating(true);

      // Dynamically import html2canvas and jspdf to keep initial bundle size light
      const [html2canvasModule, jsPDFModule] = await Promise.all([
        import("html2canvas"),
        import("jspdf"),
      ]);

      const html2canvas = html2canvasModule.default;
      const jsPDF = jsPDFModule.jsPDF;

      const container = reportRef.current;
      const sections = container.querySelectorAll<HTMLElement>("[data-pdf-section]");

      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

      const pageWidth = 210;
      const pageHeight = 297;
      const margin = 10;
      const printableWidth = pageWidth - margin * 2;
      const printableHeight = pageHeight - margin * 2;

      let currentY = margin;
      let pageNumber = 1;

      // Target section elements or entire container
      const elementsToRender =
        sections.length > 0
          ? Array.from(sections)
          : [container];

      for (let i = 0; i < elementsToRender.length; i++) {
        const el = elementsToRender[i];

        const canvas = await html2canvas(el, {
          scale: 2,
          useCORS: true,
          logging: false,
          backgroundColor: "#ffffff",
          windowWidth: 1200,
        });

        const imgData = canvas.toDataURL("image/png");
        const imgHeight = (canvas.height * printableWidth) / canvas.width;

        // If not the first page element and adding this section exceeds printable page height
        if (i > 0 && currentY + imgHeight > printableHeight + margin) {
          pdf.addPage();
          pageNumber++;
          currentY = margin;
        }

        // Add section image to PDF
        pdf.addImage(
          imgData,
          "PNG",
          margin,
          currentY,
          printableWidth,
          imgHeight,
          undefined,
          "FAST"
        );

        currentY += imgHeight + 6;
      }

      // Add simple page numbering footer
      const totalPages = pageNumber;
      for (let p = 1; p <= totalPages; p++) {
        pdf.setPage(p);
        pdf.setFontSize(8);
        pdf.setTextColor(148, 163, 184); // slate-400
        pdf.text(
          `Page ${p} of ${totalPages} • Generated by Reportly`,
          pageWidth / 2,
          pageHeight - 5,
          { align: "center" }
        );
      }

      // Sanitize filename
      const cleanClient = clientName.replace(/[^a-zA-Z0-9_-]/g, "_");
      const cleanStart = startDate.replace(/[^a-zA-Z0-9_-]/g, "_");
      const cleanEnd = endDate.replace(/[^a-zA-Z0-9_-]/g, "_");
      const filename = `Reportly_${cleanClient}_${cleanStart}_to_${cleanEnd}.pdf`;

      pdf.save(filename);
    } catch (err) {
      console.error("Failed to generate PDF:", err);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <Button
      onClick={handleDownloadPDF}
      disabled={isGenerating}
      className={className || "bg-slate-900 hover:bg-slate-800 text-white dark:bg-slate-100 dark:text-slate-900 dark:hover:bg-slate-200 gap-2 shadow-sm font-medium text-xs"}
    >
      {isGenerating ? (
        <>
          <Loader2 className="h-3.5 w-3.5 animate-spin" />
          <span>Generating PDF...</span>
        </>
      ) : (
        <>
          <Download className="h-3.5 w-3.5" />
          <span>Download PDF</span>
        </>
      )}
    </Button>
  );
}
