"use client";

import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { sendReportEmailAction } from "@/app/actions/email";
import { ToastBanner, ToastMessage } from "@/components/ui/toast";
import { Mail, Send, Loader2, Paperclip, CheckCircle2 } from "lucide-react";

interface SendReportDialogProps {
  isOpen: boolean;
  onOpenChange: (open: boolean) => void;
  reportRef: React.RefObject<HTMLDivElement | null>;
  clientId: string;
  clientName: string;
  startDate: string;
  endDate: string;
  agencyName: string;
  onSuccess?: () => void;
}

export function SendReportDialog({
  isOpen,
  onOpenChange,
  reportRef,
  clientId,
  clientName,
  startDate,
  endDate,
  agencyName,
  onSuccess,
}: SendReportDialogProps) {
  const [isSending, setIsSending] = useState(false);
  const [toast, setToast] = useState<ToastMessage | null>(null);

  // Pre-filled defaults
  const cleanClientSlug = clientName.toLowerCase().replace(/[^a-z0-9]/g, "");
  const defaultEmail = `contact@${cleanClientSlug || "client"}.com`;
  const defaultSubject = `[${agencyName}] Performance Overview Report for ${clientName} (${startDate} – ${endDate})`;
  const defaultMessage = `Hi ${clientName} Team,\n\nAttached is your marketing performance overview report for the period of ${startDate} to ${endDate}.\n\nPlease review the attached PDF breakdown and let us know if you have any questions or feedback.\n\nBest regards,\n${agencyName}`;

  const [recipientEmail, setRecipientEmail] = useState(defaultEmail);
  const [subject, setSubject] = useState(defaultSubject);
  const [message, setMessage] = useState(defaultMessage);

  const cleanClient = clientName.replace(/[^a-zA-Z0-9_-]/g, "_");
  const cleanStart = startDate.replace(/[^a-zA-Z0-9_-]/g, "_");
  const cleanEnd = endDate.replace(/[^a-zA-Z0-9_-]/g, "_");
  const filename = `Reportly_${cleanClient}_${cleanStart}_to_${cleanEnd}.pdf`;

  const handleSendEmail = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!recipientEmail || !recipientEmail.includes("@")) {
      setToast({
        id: "email-invalid-err",
        type: "error",
        title: "Invalid Email Address",
        description: "Please enter a valid recipient email address.",
      });
      return;
    }

    if (!reportRef.current) {
      setToast({
        id: "ref-err",
        type: "error",
        title: "Report Unavailable",
        description: "Could not locate report view element for rendering.",
      });
      return;
    }

    try {
      setIsSending(true);

      // Dynamically import html2canvas and jspdf
      const [html2canvasModule, jsPDFModule] = await Promise.all([
        import("html2canvas"),
        import("jspdf"),
      ]);

      const html2canvas = html2canvasModule.default;
      const jsPDF = jsPDFModule.jsPDF;

      const container = reportRef.current;
      const sections = container.querySelectorAll<HTMLElement>("[data-pdf-section]");

      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

      const pageWidth = 210;
      const pageHeight = 297;
      const margin = 10;
      const printableWidth = pageWidth - margin * 2;
      const printableHeight = pageHeight - margin * 2;

      let currentY = margin;
      let pageNumber = 1;

      const elementsToRender =
        sections.length > 0
          ? Array.from(sections)
          : [container];

      for (let i = 0; i < elementsToRender.length; i++) {
        const el = elementsToRender[i];

        const canvas = await html2canvas(el, {
          scale: 2,
          useCORS: true,
          logging: false,
          backgroundColor: "#ffffff",
          windowWidth: 1200,
        });

        const imgData = canvas.toDataURL("image/png");
        const imgHeight = (canvas.height * printableWidth) / canvas.width;

        if (i > 0 && currentY + imgHeight > printableHeight + margin) {
          pdf.addPage();
          pageNumber++;
          currentY = margin;
        }

        pdf.addImage(
          imgData,
          "PNG",
          margin,
          currentY,
          printableWidth,
          imgHeight,
          undefined,
          "FAST"
        );

        currentY += imgHeight + 6;
      }

      // Add simple footer
      const totalPages = pageNumber;
      for (let p = 1; p <= totalPages; p++) {
        pdf.setPage(p);
        pdf.setFontSize(8);
        pdf.setTextColor(148, 163, 184);
        pdf.text(
          `Page ${p} of ${totalPages} • Generated by Reportly`,
          pageWidth / 2,
          pageHeight - 5,
          { align: "center" }
        );
      }

      // Output PDF as base64 string
      const pdfBase64 = pdf.output("datauristring");

      // Dispatch to Server Action
      const result = await sendReportEmailAction({
        clientId,
        recipientEmail,
        subject,
        message,
        pdfBase64,
        filename,
        startDate,
        endDate,
      });

      if (result.error) {
        setToast({
          id: "email-send-error",
          type: "error",
          title: "Dispatch Failed",
          description: result.error,
        });
      } else {
        setToast({
          id: "email-send-success",
          type: "success",
          title: "Report Email Sent!",
          description: result.mocked
            ? `[MOCK MODE] Email payload logged for ${recipientEmail}`
            : `Successfully sent report email with PDF attachment to ${recipientEmail}`,
        });

        if (onSuccess) onSuccess();

        setTimeout(() => {
          onOpenChange(false);
        }, 1200);
      }
    } catch (err) {
      setToast({
        id: "email-catch-err",
        type: "error",
        title: "An error occurred",
        description: err instanceof Error ? err.message : "Failed to generate or send report.",
      });
    } finally {
      setIsSending(false);
    }
  };

  return (
    <>
      <ToastBanner message={toast} onClose={() => setToast(null)} />

      <Dialog open={isOpen} onOpenChange={onOpenChange}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <div className="flex items-center gap-2 text-blue-600 dark:text-blue-400">
              <Mail className="h-5 w-5" />
              <DialogTitle>Send Report to Client</DialogTitle>
            </div>
            <DialogDescription className="text-xs">
              Email the branded PDF performance report directly to {clientName}.
            </DialogDescription>
          </DialogHeader>

          <form onSubmit={handleSendEmail} className="space-y-4 pt-2">
            {/* Recipient Email */}
            <div className="space-y-1">
              <label className="text-xs font-medium text-slate-700 dark:text-slate-300">
                To (Recipient Email) <span className="text-rose-500">*</span>
              </label>
              <Input
                type="email"
                required
                value={recipientEmail}
                onChange={(e) => setRecipientEmail(e.target.value)}
                placeholder="client@company.com"
                className="text-xs"
              />
            </div>

            {/* Email Subject */}
            <div className="space-y-1">
              <label className="text-xs font-medium text-slate-700 dark:text-slate-300">
                Subject Line <span className="text-rose-500">*</span>
              </label>
              <Input
                type="text"
                required
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                placeholder="Report Subject"
                className="text-xs"
              />
            </div>

            {/* Custom Note / Message */}
            <div className="space-y-1">
              <label className="text-xs font-medium text-slate-700 dark:text-slate-300">
                Custom Message / Note
              </label>
              <textarea
                rows={4}
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                placeholder="Add a personalized note for your client..."
                className="w-full rounded-md border border-slate-200 bg-white p-2.5 text-xs text-slate-900 shadow-xs focus:border-blue-500 focus:outline-none dark:border-slate-800 dark:bg-slate-900 dark:text-slate-100"
              />
            </div>

            {/* Attachment Banner */}
            <div className="flex items-center justify-between rounded-lg border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-900/60 p-2.5 text-xs">
              <div className="flex items-center gap-2 text-slate-600 dark:text-slate-300">
                <Paperclip className="h-4 w-4 text-slate-400" />
                <span className="font-mono text-[11px] truncate max-w-[240px]">
                  {filename}
                </span>
              </div>
              <span className="text-[10px] font-semibold text-emerald-600 dark:text-emerald-400 flex items-center gap-1">
                <CheckCircle2 className="h-3 w-3" /> Auto-Generated
              </span>
            </div>

            <DialogFooter className="pt-2">
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => onOpenChange(false)}
                disabled={isSending}
                className="text-xs"
              >
                Cancel
              </Button>
              <Button
                type="submit"
                disabled={isSending}
                size="sm"
                className="bg-blue-600 hover:bg-blue-700 text-white text-xs gap-2 font-medium"
              >
                {isSending ? (
                  <>
                    <Loader2 className="h-3.5 w-3.5 animate-spin" />
                    <span>Generating & Sending...</span>
                  </>
                ) : (
                  <>
                    <Send className="h-3.5 w-3.5" />
                    <span>Send Report</span>
                  </>
                )}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </>
  );
}
